### ISSUE TITLE
About the public key rolling

### ISSUE THREAD

**Issue by itewqq** [positive-security/send-my#2]
Hi, in your article I noticed that the pairing procedure is:
`When paring an AirTag with an Apple Device, an Elliptic Curve key pair is generated and the public key is pushed to the AirTag (and a shared secret to generate rolling public keys)`

I’m confused about whether the private key will be stored in the airtag, because from the paper https://arxiv.org/pdf/2103.02282.pdf section 6.1, it seems that if you don’t know the d_i then you can’t calculate the next p_i?

Would be appreciated if you can clarify this 🤣 thanks!

**Comment by jmz1** [comment]
There is no key pair, and no airtag. Just a series of arbitrary public keys. Perhaps you should be asking on the OpenHaystack project?

**Comment by itewqq** [comment]
@jmz1 Actually my question is about the description in the article https://positive.security/blog/send-my :
`No secrets on the AirTag`

How could the airtag rolling its public key without knowing the private key?

**Comment by breakingsystems** [comment]
I had another look: According to the [Apple specification](https://images.frandroid.com/wp-content/uploads/2020/06/Find_My_network_accessory_protocol_specification.pdf) (section 6.3.4.1.), only the public key P is stored on the device and the rolling public key is generated as `P_i = u_i ⋅ P  + v_i ⋅ G` where `u_i` and `v_i` are derived from the shared secret via the key derivation function.
