### ISSUE TITLE
Problem Flashing with ESP32 (ESPRESSIF)

### ISSUE THREAD

**Issue by KatzeMau** [positive-security/send-my#5]
I cant flash on my macbook, its the same error as https://github.com/seemoo-lab/openhaystack/issues/66

mac@MacBook-Pro ~/D/s/F/ESP32 (main) [1]> ./flash_esp32.sh -p /dev/cu.usbmodem14101
esptool.py v3.1
Found 2 serial ports
Serial port /dev/cu.usbmodem14101
Connecting......
Detecting chip type... ESP32
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 3c:61:05:12:48:2c
Uploading stub...

A fatal error occurred: Failed to write to target RAM (result was 01070000)
mac@MacBook-Pro ~/D/s/F/ESP32 (main) [2]>

**Comment by breakingsystems** [comment]
The issue seems better to be discussed in the linked openhaystack issue as it's not specific to Send My.
